---
title: "Germinacion en semillas de garbanzo"
format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    embed-resources: true
    output-file: index 
---
# Cargar librerias
```{r}
source("https://inkaverse.com/setup.r")
library(tidyverse)
library(GerminaR)
```

# Importar datos
```{r}
url <- "https://docs.google.com/spreadsheets/d/16eZ0pfgKOVMiMsAfz5IzCG9rTSpA0nHeiMpe4MsDcMM/edit?gid=0#gid=0"

gs <- as_sheets_id(url)

fb <- range_read(gs
                 , sheet = "fb") %>% 
  mutate(across(Tratamiento,  ~as.factor(.))) %>% 
  as.data.frame()
str(fb)
```

## Análisis de Germinación

```{r}
gsm <- ger_summary(SeedN = "seeds"
                   , evalName = "d"
                   , data = fb
                   )
gsm %>% kable()

```

## Porcentaje de Germinación (GRP)

```{r}

av <- aov(grp ~ Tratamiento, data = gsm)
anova(av)


mc_grp <- ger_testcomp(aov = av
                       , comp = c("Tratamiento")
                       , type = "snk"
                       )

mc_grp$table %>% 
   kable(caption = "Mean germinacion time comparison")

grp <- mc_grp$table %>% 
   fplot(data = .
       , type = "bar"
       , x = "Tratamiento"
       , y = "grp"
       , group = "Tratamiento"
       , ylimits = c(0, 120, 30)
       , ylab = "Germinación ('%')"
       , xlab = "Escarificación de semillas"
       , error = "ste"
       , sig = "sig"
       , color = T 
       )

grp
```

## Germinación en el tiempo (MGT)

```{r}

av <- aov(mgt ~ Tratamiento, data = gsm)
anova(av)

mc_mgt <- ger_testcomp(aov = av
                       , comp = c("Tratamiento")
                       , type = "snk")

mc_mgt$table %>% 
   kable(caption = "Mean germination time comparison")

mgt <- mc_mgt$table %>% 
   fplot(data = .
       , type = "bar" 
       , x = "Tratamiento"
       , y = "mgt"
       , group = "Tratamiento"
       , ylimits = c(0,10, 1)
       , ylab = "Germinación en el tiempo (Días)"
       , xlab = "Escarificación de semillas"
       , sig = "sig"
       , error = "ste"
       , color = T
       )

mgt
```

## Análisis acumulativo de germinación

```{r}

git <- ger_intime(Factor = "Tratamiento"
                  , SeedN = "seeds"
                  , evalName = "d"
                  , method = "percentage"
                  , data = fb
                  )

git %>% 
   head(10) %>% 
   kable(caption = "Acumulación de germinación por método de escarificación")

Tratamiento <- git %>% 
   fplot(data = .
        , type = "line"
        , x = "evaluation"
        , y = "mean"
        , group = "Tratamiento"
        , ylimits = c(0, 110, 10)
        , ylab = "Germinación ('%')"
        , xlab = "Dias"
        , glab = "Tratamiento"
        , color = T
        , error = "ste"
        )
Tratamiento
```

## Índice de sincronización (SYN)

```{r}
av <- aov(syn ~ Tratamiento, data = gsm)
anova(av)


mc_syn <- ger_testcomp(aov = av
                       , comp = "Tratamiento"
                       , type = "snk"
                       )

mc_syn$table %>% 
   kable(caption = "Mean germination time comparison")


syn <- mc_syn$table %>% 
   fplot(data = .
       , type = "bar" 
       , x = "Tratamiento"
       , y = "syn"
       , group = "Tratamiento"
       , ylimits = c(0,1, 0.1)
       , ylab = "Índice de sincronización"
       , xlab = "Métodos de escarificación"
       , glab = "Tratamiento"
       , sig = "sig"
       , error = "ste"
       , color = T
       )

syn

```

